namespace DisCatSharp.Hosting.AspNetCore.Ingress.OAuth;

/// <summary>
///     Configures the Discord OAuth callback flow exposed by the ASP.NET Core ingress package.
/// </summary>
/// <remarks>
///     <see cref="ClientId" />, <see cref="ClientSecret" />, and <see cref="RedirectUri" /> must be configured together before the
///     default callback handler can exchange authorization codes.
/// </remarks>
public sealed class DiscordOAuthIngressOptions
{
	/// <summary>
	///     The default logical flow name used when storing pending OAuth state.
	/// </summary>
	public const string DefaultPendingStateFlow = "oauth";

	/// <summary>
	///     Gets or sets the Discord application client identifier used for token exchange.
	/// </summary>
	/// <remarks>
	///     Leave this at <c>0</c> only when the OAuth callback endpoint is intentionally disabled.
	/// </remarks>
	public ulong ClientId { get; set; }

	/// <summary>
	///     Gets or sets the Discord application client secret used for token exchange.
	/// </summary>
	/// <remarks>
	///     This value is consumed only by <see cref="IDiscordOAuthTokenExchangeService" /> implementations and should be sourced from a
	///     secure configuration provider.
	/// </remarks>
	public string? ClientSecret { get; set; }

	/// <summary>
	///     Gets or sets the redirect URI that Discord should use for the authorization-code callback.
	/// </summary>
	/// <remarks>
	///     The default callback handler compares this URI against the stored authorization request to prevent redirect swapping.
	/// </remarks>
	public string? RedirectUri { get; set; }

	/// <summary>
	///     Gets or sets the expected logical flow name for pending OAuth state entries.
	/// </summary>
	/// <remarks>
	///     This value must match <see cref="DiscordIngressPendingState.Flow" /> for states generated by the corresponding authorization
	///     flow.
	/// </remarks>
	public string PendingStateFlow { get; set; } = DefaultPendingStateFlow;

	/// <summary>
	///     Gets a value indicating whether the OAuth callback flow has enough configuration to exchange codes.
	/// </summary>
	public bool IsConfigured
		=> this.ClientId != 0 && !string.IsNullOrWhiteSpace(this.ClientSecret) && !string.IsNullOrWhiteSpace(this.RedirectUri);
}
