using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.BaseHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordHostedService.ConfigureAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordHostedService.ConfigureExtensionsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordHostedService.ConnectAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordShardedHostedService.ConfigureAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordShardedHostedService.ConfigureExtensionsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordShardedHostedService.ConnectAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "PropertyDocumentationHeader:The property must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~P:DisCatSharp.Hosting.DiscordShardedHostedService.ShardedClient")]
[assembly: SuppressMessage("DocumentationHeader", "PropertyDocumentationHeader:The property must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~P:DisCatSharp.Hosting.IDiscordHostedShardService.ShardedClient")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.BaseHostedService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.BaseHostedService.InitializeExtensions(DisCatSharp.DiscordClient)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordHostedService.ConfigureAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Hosting.DiscordShardedHostedService.ConfigureAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "DCS0102:[Discord] Deprecated", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0101:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0103:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0001:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0002:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>")]
