//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisCatSharp.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisCatSharp.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisCatSharp considers this as deprecated. Update your code..
        /// </summary>
        internal static string AnalyzerDescriptionDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord deprecated this..
        /// </summary>
        internal static string AnalyzerDescriptionDiscordDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionDiscordDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord has released it as experiment. Do not use in production..
        /// </summary>
        internal static string AnalyzerDescriptionDiscordInExperiment {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionDiscordInExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord hasn&apos;t released this yet. Do not use in production..
        /// </summary>
        internal static string AnalyzerDescriptionDiscordUnreleased {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionDiscordUnreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisCatSharp considers this as experimental. Do not use in production..
        /// </summary>
        internal static string AnalyzerDescriptionExperimental {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This needs special features to be enabled / set..
        /// </summary>
        internal static string AnalyzerDescriptionRequiresFeature {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionRequiresFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is deprecated: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is deprecated: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatDiscordDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatDiscordDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is in experiment: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatDiscordInExperiment {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatDiscordInExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is not released yet: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatDiscordUnreleased {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatDiscordUnreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is experimental: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatExperimental {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; needs features: {2}.
        /// </summary>
        internal static string AnalyzerMessageFormatRequiresFeature {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatRequiresFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DCS] Deprecated.
        /// </summary>
        internal static string AnalyzerTitleDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerTitleDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Discord] Deprecated.
        /// </summary>
        internal static string AnalyzerTitleDiscordDeprecated {
            get {
                return ResourceManager.GetString("AnalyzerTitleDiscordDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Discord] InExperiment.
        /// </summary>
        internal static string AnalyzerTitleDiscordInExperiment {
            get {
                return ResourceManager.GetString("AnalyzerTitleDiscordInExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Discord] Unreleased.
        /// </summary>
        internal static string AnalyzerTitleDiscordUnreleased {
            get {
                return ResourceManager.GetString("AnalyzerTitleDiscordUnreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DCS] Experimental.
        /// </summary>
        internal static string AnalyzerTitleExperimental {
            get {
                return ResourceManager.GetString("AnalyzerTitleExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Discord] Requires Features.
        /// </summary>
        internal static string AnalyzerTitleRequiresFeature {
            get {
                return ResourceManager.GetString("AnalyzerTitleRequiresFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Faulty {
            get {
                return ResourceManager.GetString("Faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling .
        /// </summary>
        internal static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
    }
}
