// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace DisCatSharp.Analyzer
{
    internal sealed partial class Vsix
    {
        public const string Id = "DisCatSharp.Analyzer.a1051cd0-d47d-4397-9917-6a6b45737ea9";
        public const string Name = "DisCatSharp Analyzer";
        public const string Description = @"DisCatSharp Analyzer Extension for Development";
        public const string Language = "en-US";
        public const string Version = "5.3";
        public const string Author = "AITSYS";
        public const string Tags = "DisCatSharp,Analyzer";
    }
}
